-- Supabase schema for Digital Trust Solutions chat and lead tracking.
-- Run this in Supabase SQL Editor, then copy your Project URL and anon key
-- into SUPABASE_URL and SUPABASE_ANON_KEY in script.js.

create table if not exists public.chat_interactions (
  id bigint generated by default as identity primary key,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  page text,
  user_agent text,
  language text,
  created_at timestamptz not null default now()
);

alter table public.chat_interactions enable row level security;

drop policy if exists "Allow public inserts for website chat" on public.chat_interactions;

create policy "Allow public inserts for website chat"
on public.chat_interactions
for insert
to anon
with check (true);

drop policy if exists "Authenticated users can read chat interactions" on public.chat_interactions;

create policy "Authenticated users can read chat interactions"
on public.chat_interactions
for select
to authenticated
using (true);

create index if not exists chat_interactions_created_at_idx
on public.chat_interactions (created_at desc);

create index if not exists chat_interactions_event_type_idx
on public.chat_interactions (event_type);
