-- Digital Trust Solutions CRM-lite database for Supabase.
-- Run this file in Supabase SQL Editor.
-- Then copy Project URL and anon public key into script.js.

create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text not null,
  language text not null default 'es',
  label text,
  value text not null,
  is_published boolean not null default true,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  unique (content_key, language)
);

create table if not exists public.site_assets (
  id bigint generated by default as identity primary key,
  asset_slot text not null,
  title text,
  file_url text not null,
  alt_text text,
  is_active boolean not null default true,
  uploaded_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id),
  action text not null,
  target_table text,
  target_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  page text,
  language text,
  user_agent text,
  lead_status text not null default 'new',
  notes text
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender text not null check (sender in ('user', 'bot', 'cliente', 'system')),
  message text not null,
  page text,
  language text,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  session_id text not null,
  source text not null default 'website',
  status text not null default 'new',
  name text,
  email text,
  phone text,
  service text,
  budget text,
  urgency text,
  message text,
  notes text,
  transcript text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leads add column if not exists notes text;

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  session_id text not null,
  name text not null,
  email text not null,
  phone text,
  service text not null,
  budget text,
  message text not null,
  notification_ok boolean,
  welcome_ok boolean,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.interaction_events (
  id bigint generated by default as identity primary key,
  session_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  page text,
  user_agent text,
  language text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function public.prevent_more_than_five_active_admins()
returns trigger as $$
begin
  if new.is_active = true and (
    select count(*)
    from public.admin_profiles
    where is_active = true
      and user_id <> coalesce(new.user_id, '00000000-0000-0000-0000-000000000000'::uuid)
  ) >= 5 then
    raise exception 'Only five active admin users are allowed';
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists limit_active_admins on public.admin_profiles;

create trigger limit_active_admins
before insert or update on public.admin_profiles
for each row
execute function public.prevent_more_than_five_active_admins();

drop trigger if exists set_leads_updated_at on public.leads;

create trigger set_leads_updated_at
before update on public.leads
for each row
execute function public.set_updated_at();

drop trigger if exists set_site_content_updated_at on public.site_content;

create trigger set_site_content_updated_at
before update on public.site_content
for each row
execute function public.set_updated_at();

drop trigger if exists set_site_assets_updated_at on public.site_assets;

create trigger set_site_assets_updated_at
before update on public.site_assets
for each row
execute function public.set_updated_at();

create or replace function public.is_active_admin()
returns boolean as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = auth.uid()
      and is_active = true
  );
$$ language sql security definer set search_path = public;

alter table public.admin_profiles enable row level security;
alter table public.site_content enable row level security;
alter table public.site_assets enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.leads enable row level security;
alter table public.contact_requests enable row level security;
alter table public.interaction_events enable row level security;

drop policy if exists "Admins can read admin profiles" on public.admin_profiles;
create policy "Admins can read admin profiles"
on public.admin_profiles for select to authenticated
using (public.is_active_admin() or user_id = auth.uid());

drop policy if exists "Admins can manage admin profiles" on public.admin_profiles;
create policy "Admins can manage admin profiles"
on public.admin_profiles for all to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

drop policy if exists "Public can read published site content" on public.site_content;
create policy "Public can read published site content"
on public.site_content for select to anon, authenticated
using (is_published = true);

drop policy if exists "Admins can manage site content" on public.site_content;
create policy "Admins can manage site content"
on public.site_content for all to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

drop policy if exists "Public can read active site assets" on public.site_assets;
create policy "Public can read active site assets"
on public.site_assets for select to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage site assets" on public.site_assets;
create policy "Admins can manage site assets"
on public.site_assets for all to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

drop policy if exists "Admins can read audit log" on public.admin_audit_log;
create policy "Admins can read audit log"
on public.admin_audit_log for select to authenticated
using (public.is_active_admin());

drop policy if exists "Admins can insert audit log" on public.admin_audit_log;
create policy "Admins can insert audit log"
on public.admin_audit_log for insert to authenticated
with check (public.is_active_admin());

drop policy if exists "Public can insert chat sessions" on public.chat_sessions;
create policy "Public can insert chat sessions"
on public.chat_sessions for insert to anon
with check (true);

drop policy if exists "Public can update chat sessions" on public.chat_sessions;
create policy "Public can update chat sessions"
on public.chat_sessions for update to anon
using (true)
with check (true);

drop policy if exists "Public can insert chat messages" on public.chat_messages;
create policy "Public can insert chat messages"
on public.chat_messages for insert to anon
with check (true);

drop policy if exists "Public can insert leads" on public.leads;
create policy "Public can insert leads"
on public.leads for insert to anon
with check (true);

drop policy if exists "Public can insert contact requests" on public.contact_requests;
create policy "Public can insert contact requests"
on public.contact_requests for insert to anon
with check (true);

drop policy if exists "Public can insert interaction events" on public.interaction_events;
create policy "Public can insert interaction events"
on public.interaction_events for insert to anon
with check (true);

drop policy if exists "Authenticated can read chat sessions" on public.chat_sessions;
drop policy if exists "Admins can read chat sessions" on public.chat_sessions;
create policy "Admins can read chat sessions"
on public.chat_sessions for select to authenticated
using (public.is_active_admin());

drop policy if exists "Authenticated can read chat messages" on public.chat_messages;
drop policy if exists "Admins can read chat messages" on public.chat_messages;
create policy "Admins can read chat messages"
on public.chat_messages for select to authenticated
using (public.is_active_admin());

drop policy if exists "Authenticated can read leads" on public.leads;
drop policy if exists "Admins can read leads" on public.leads;
create policy "Admins can read leads"
on public.leads for select to authenticated
using (public.is_active_admin());

drop policy if exists "Authenticated can update leads" on public.leads;
drop policy if exists "Admins can update leads" on public.leads;
create policy "Admins can update leads"
on public.leads for update to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

drop policy if exists "Authenticated can read contact requests" on public.contact_requests;
drop policy if exists "Admins can read contact requests" on public.contact_requests;
create policy "Admins can read contact requests"
on public.contact_requests for select to authenticated
using (public.is_active_admin());

drop policy if exists "Authenticated can read interaction events" on public.interaction_events;
drop policy if exists "Admins can read interaction events" on public.interaction_events;
create policy "Admins can read interaction events"
on public.interaction_events for select to authenticated
using (public.is_active_admin());

create index if not exists chat_sessions_last_seen_at_idx
on public.chat_sessions (last_seen_at desc);

create index if not exists chat_messages_session_id_created_at_idx
on public.chat_messages (session_id, created_at);

create index if not exists leads_created_at_idx
on public.leads (created_at desc);

create index if not exists leads_session_id_idx
on public.leads (session_id);

create index if not exists leads_status_idx
on public.leads (status);

create index if not exists contact_requests_created_at_idx
on public.contact_requests (created_at desc);

create index if not exists interaction_events_session_id_created_at_idx
on public.interaction_events (session_id, created_at);

create index if not exists interaction_events_event_type_idx
on public.interaction_events (event_type);

create or replace view public.lead_summary
with (security_invoker = true) as
select
  l.id,
  l.session_id,
  l.source,
  l.status,
  l.name,
  l.email,
  l.phone,
  l.service,
  l.budget,
  l.urgency,
  l.message,
  l.notes,
  l.created_at,
  l.updated_at,
  count(cm.id) as chat_message_count,
  max(cm.created_at) as last_chat_message_at
from public.leads l
left join public.chat_messages cm on cm.session_id = l.session_id
group by l.id;

create or replace view public.session_timeline
with (security_invoker = true) as
select
  session_id,
  created_at,
  'chat_message' as activity_type,
  sender as actor,
  message as detail,
  jsonb_build_object('page', page, 'language', language) as metadata
from public.chat_messages
union all
select
  session_id,
  created_at,
  'contact_request' as activity_type,
  'cliente' as actor,
  concat(name, ' solicito ', service, ' con presupuesto ', budget) as detail,
  metadata
from public.contact_requests
union all
select
  session_id,
  created_at,
  event_type as activity_type,
  'system' as actor,
  event_type as detail,
  payload as metadata
from public.interaction_events;
